// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhvbmD81QiZ9eKjBZVAmxatR2Rf1jBVk',
    appId: '1:136707314322:web:89dea4912c65b4a8c68c4b',
    messagingSenderId: '136707314322',
    projectId: 'pet-care-app-40949',
    authDomain: 'pet-care-app-40949.firebaseapp.com',
    storageBucket: 'pet-care-app-40949.firebasestorage.app',
    measurementId: 'G-DCEQC7640C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3hgKHYfAHYjaJx015A31fVPBnm4jiFw',
    appId: '1:136707314322:android:599d64fdd67c84b8c68c4b',
    messagingSenderId: '136707314322',
    projectId: 'pet-care-app-40949',
    storageBucket: 'pet-care-app-40949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCosnzJMNNvN15AMiUJ4xzyLH18FoL1Huc',
    appId: '1:136707314322:ios:6a3040c083c795d0c68c4b',
    messagingSenderId: '136707314322',
    projectId: 'pet-care-app-40949',
    storageBucket: 'pet-care-app-40949.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCosnzJMNNvN15AMiUJ4xzyLH18FoL1Huc',
    appId: '1:136707314322:ios:6a3040c083c795d0c68c4b',
    messagingSenderId: '136707314322',
    projectId: 'pet-care-app-40949',
    storageBucket: 'pet-care-app-40949.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOhvbmD81QiZ9eKjBZVAmxatR2Rf1jBVk',
    appId: '1:136707314322:web:1ea130089fe01f68c68c4b',
    messagingSenderId: '136707314322',
    projectId: 'pet-care-app-40949',
    authDomain: 'pet-care-app-40949.firebaseapp.com',
    storageBucket: 'pet-care-app-40949.firebasestorage.app',
    measurementId: 'G-TVGPLLNL6W',
  );
}
